// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SmallTalkClient;

{$R *.RES}
{ITE} {LCID:00000409:00000419} {}
{ITE} {DFMFileType} {AddContact.dfm}
{ITE} {DFMFileType} {ChangeDisplayName.dfm}
{ITE} {DFMFileType} {ChangePassword.dfm}
{ITE} {DFMFileType} {Client.dfm}
{ITE} {DFMFileType} {ConnectionSettings.dfm}
{ITE} {DFMFileType} {Log.dfm}
{ITE} {DFMFileType} {MessageList.dfm}
{ITE} {DFMFileType} {NewAccount.dfm}
{ITE} {DFMFileType} {NewMessage.dfm}
{ITE} {DFMFileType} {ReceivedMessage.dfm}
{ITE} {DFMFileType} {UserSettings.dfm}
{ITE} {RCFileType} {TrayIcons.rc}
{ITE} {RCFileType} {SmallTalkClient_DRC.rc}

{$R 'AddContact.dfm' AddContactForm:TForm}
{$R 'ChangeDisplayName.dfm' ChangeDisplayNameForm:TForm}
{$R 'ChangePassword.dfm' ChangePasswordForm:TForm}
{$R 'Client.dfm' ClientForm:TForm}
{$R 'ConnectionSettings.dfm' ConnectionSettingsForm:TForm}
{$R 'Log.dfm' LogForm:TForm}
{$R 'MessageList.dfm' MessageListForm:TForm}
{$R 'NewAccount.dfm' NewAccountForm:TForm}
{$R 'NewMessage.dfm' NewMessageForm:TForm}
{$R 'ReceivedMessage.dfm' ReceivedMessageForm:TForm}
{$R 'UserSettings.dfm' UserSettingsForm:TForm}
{$R 'TrayIcons.res' 'TrayIcons.rc'}
{$R 'SmallTalkClient_DRC.res' 'SmallTalkClient_DRC.rc'}

{$E RUS}

begin
end.